@startuml
class OutputFile{
__private data__
String filename;
__Constructor__
+public OutputFile()
..Simple Setter..
+public void setOutputFile(String filename)
..Methods..
+public String getOutputFile()
}
@enduml